-- 'SmiteshP/nvim-navic'
return function(c, s)
    return {
        { 'NavicIconsFile', c.secondary_accent, c.secondary_fg },
        { 'NavicIconsModule', c.secondary_accent, c.secondary_fg },
        { 'NavicIconsNamespace', c.yellow, c.secondary_fg },
        { 'NavicIconsPackage', c.orange, c.secondary_fg },
        { 'NavicIconsClass', c.yellow, c.secondary_fg },
        { 'NavicIconsMethod', c.violet, c.secondary_fg },
        { 'NavicIconsProperty', c.secondary_accent, c.secondary_fg },
        { 'NavicIconsField', c.secondary_accent, c.secondary_fg },
        { 'NavicIconsConstructor', c.yellow, c.secondary_fg },
        { 'NavicIconsEnum', c.yellow, c.secondary_fg },
        { 'NavicIconsInterface', c.yellow, c.secondary_fg },
        { 'NavicIconsFunction', c.violet, c.secondary_fg },
        { 'NavicIconsVariable', c.secondary_accent, c.secondary_fg },
        { 'NavicIconsConstant', c.orange, c.secondary_fg },
        { 'NavicIconsString', c.green, c.secondary_fg },
        { 'NavicIconsNumber', c.orange, c.secondary_fg },
        { 'NavicIconsBoolean', c.orange, c.secondary_fg },
        { 'NavicIconsArray', c.yellow, c.secondary_fg },
        { 'NavicIconsObject', c.orange, c.secondary_fg },
        { 'NavicIconsKey', c.violet, c.secondary_fg },
        { 'NavicIconsNull', c.red, c.secondary_fg },
        { 'NavicIconsEnumMember', c.primary_accent, c.secondary_fg },
        { 'NavicIconsStruct', c.yellow, c.secondary_fg },
        { 'NavicIconsEvent', c.violet, c.secondary_fg },
        { 'NavicIconsOperator', c.violet, c.secondary_fg },
        { 'NavicIconsTypeParameter', c.yellow, c.secondary_fg },
        { 'NavicText', c.white, c.secondary_fg },
        { 'NavicSeparator', c.primary_accent, c.secondary_fg },
    }
end
